version: "3.5"

networks:
  webb:
    driver: bridge

services:
  athena_chain:
    image: trufflesuite/ganache:latest
    container_name: athena-chain
    ports:
      - ${ATHENA_CHAIN_PORT}:8545
    volumes:
      - ./data/athena_chain:/data
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${ATHENA_CHAIN_ID}"
    command:
      - "--chain.chainId=${ATHENA_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=false"
      - "--logging.verbose=false"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  hermes_chain:
    image: trufflesuite/ganache:latest
    container_name: hermes-chain
    ports:
      - ${HERMES_CHAIN_PORT}:8545
    volumes:
      - ./data/hermes_chain:/data
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${HERMES_CHAIN_ID}"
    command:
      - "--chain.chainId=${HERMES_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=false"
      - "--logging.verbose=false"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  demeter_chain:
    image: trufflesuite/ganache:latest
    container_name: demeter-chain
    ports:
      - ${DEMETER_CHAIN_PORT}:8545
    volumes:
      - ./data/demeter_chain:/data
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${DEMETER_CHAIN_ID}"
    command:
      - "--chain.chainId=${DEMETER_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=false"
      - "--logging.verbose=false"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
