version: "3.5"

networks:
  webb:
    driver: bridge

services:
  athena_chain:
    image: ghcr.io/foundry-rs/foundry:${FOUNDRY_DOCKER_TAG}
    container_name: athena-chain
    ports:
      - ${ATHENA_CHAIN_PORT}:8545
    volumes:
      - ./data/athena_chain:/data
      - ./scripts:/scripts
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${ATHENA_CHAIN_ID}"
    command:
      - /scripts/anvil.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  hermes_chain:
    image: ghcr.io/foundry-rs/foundry:${FOUNDRY_DOCKER_TAG}
    container_name: hermes-chain
    ports:
      - ${HERMES_CHAIN_PORT}:8545
    volumes:
      - ./data/hermes_chain:/data
      - ./scripts:/scripts
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${HERMES_CHAIN_ID}"
    command:
      - /scripts/anvil.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"

  demeter_chain:
    image: ghcr.io/foundry-rs/foundry:${FOUNDRY_DOCKER_TAG}
    container_name: demeter-chain
    ports:
      - ${DEMETER_CHAIN_PORT}:8545
    volumes:
      - ./data/demeter_chain:/data
      - ./scripts:/scripts
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${DEMETER_CHAIN_ID}"
    command:
      - /scripts/anvil.sh
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
