version: "3"
services:
  db:
    image: postgres:14
    restart: always
    container_name: "postgres"
    command: postgres -c 'max_connections=600'
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - 7432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  sig-provider:
    platform: linux/x86_64
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-main}
    pull_policy: always
    restart: always
    container_name: "sig-provider"
    ports:
      - 8151:8050
  smart-contract-verifier:
    platform: linux/x86_64
    image: ghcr.io/blockscout/smart-contract-verifier:${SMART_CONTRACT_VERIFIER_DOCKER_TAG:-main}
    pull_policy: always
    restart: always
    container_name: "smart-contract-verifier"
    ports:
      - 8150:8050
  visualizer:
    platform: linux/x86_64
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    container_name: "visualizer"
    ports:
      - 8152:8050
  athena_blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "athena-blockscout"
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - .env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://athena_chain:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://athena_chain:8545/
      DATABASE_URL: postgresql://postgres:@db:5432/athena_blocksout?ssl=false
      CHAIN_ID: "${ATHENA_CHAIN_ID}"
      PORT: "${ATHENA_CHAIN_EXLORER_PORT}"
      SUBNETWORK: "${ATHENA_CHAIN_SUBNETWORK}"
    ports:
      - ${ATHENA_CHAIN_EXLORER_PORT}:${ATHENA_CHAIN_EXLORER_PORT}
    volumes:
      - ./logs/athena_blocksout/:/app/logs/

  athena_chain:
    image: trufflesuite/ganache:latest
    container_name: athena-chain
    ports:
      - "${ATHENA_CHAIN_ID}:8545"
    volumes:
      - ./data/athena_chain:/data
    command:
      - "--chain.chainId=${ATHENA_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=true"
      - "--logging.verbose=true"
  hermes_blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "hermes-blockscout"
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - .env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://hermes_chain:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://hermes_chain:8545/
      DATABASE_URL: postgresql://postgres:@db:5432/hermes_blocksout?ssl=false
      CHAIN_ID: "${HERMES_CHAIN_ID}"
      PORT: "${HERMES_CHAIN_EXLORER_PORT}"
      SUBNETWORK: "${HERMES_CHAIN_SUBNETWORK}"
    ports:
      - ${HERMES_CHAIN_EXLORER_PORT}:${HERMES_CHAIN_EXLORER_PORT}
    volumes:
      - ./logs/hermes_blocksout:/app/logs/

  hermes_chain:
    image: trufflesuite/ganache:latest
    container_name: hermes-chain
    ports:
      - "${HERMES_CHAIN_ID}:8545"
    volumes:
      - ./data/hermes_chain:/data
    command:
      - "--chain.chainId=${HERMES_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=true"
      - "--logging.verbose=true"

  demeter_blockscout:
    depends_on:
      - db
      - smart-contract-verifier
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: "demeter-blockscout"
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      - .env
    environment:
      ETHEREUM_JSONRPC_HTTP_URL: http://demeter_chain:8545/
      ETHEREUM_JSONRPC_WS_URL: ws://demeter_chain:8545/
      DATABASE_URL: postgresql://postgres:@db:5432/demeter_blocksout?ssl=false
      CHAIN_ID: "${DEMETER_CHAIN_ID}"
      PORT: "${DEMETER_CHAIN_EXLORER_PORT}"
      SUBNETWORK: "${DEMETER_CHAIN_SUBNETWORK}"
    ports:
      - ${DEMETER_CHAIN_EXLORER_PORT}:${DEMETER_CHAIN_EXLORER_PORT}
    volumes:
      - ./logs/demeter_blocksout:/app/logs/

  demeter_chain:
    image: trufflesuite/ganache:latest
    container_name: demeter-chain
    ports:
      - "${DEMETER_CHAIN_ID}:8545"
    volumes:
      - ./data/demeter_chain:/data
    command:
      - "--chain.chainId=${DEMETER_CHAIN_ID}"
      - "--database.dbPath=/data"
      - "--miner.defaultGasPrice=5000000000" # 5 gwei
      - "--wallet.mnemonic=${MNEMONIC}"
      - "--wallet.defaultBalance=10000" # 10,000 ETH
      - "--logging.debug=true"
      - "--logging.verbose=true"
