version: "3.5"

networks:
  webb:
    driver: bridge

services:
  athena_chain:
    image: ethereum/client-go:stable
    container_name: athena-chain
    ports:
      - ${ATHENA_CHAIN_PORT}:8545
    volumes:
      - ./data/athena_chain:/data
    networks:
      - webb
    env_file:
      - .env
    environment:
      CHAIN_ID: "${ATHENA_CHAIN_ID}"
    command:
      - --datadir=/data
      - --networkid=${ATHENA_CHAIN_ID}
      - --ipcdisable
      - --http
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=eth,net,web3,debug,txpool
      - --http.corsdomain=*
      - --http.vhosts=*
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.api=eth,net,web3,debug,txpool
      - --ws.origins=*
      - --graphql
      - --graphql.corsdomain=*
      - --graphql.vhosts=*
      - --nodiscover
      - --cache=512
      - --mine
      - --miner.etherbase=${VAULT_ACCOUNT_ADDRESS}
      - --allow-insecure-unlock
      - --unlock=${VAULT_ACCOUNT_ADDRESS}
      - --password=/data/password.txt
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
